# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170911_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
