# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171001_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAbleNotAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
