# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='null', upload_to=b''),
            preserve_default=False,
        ),
    ]
