# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 13:14
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(upload_to=core.utils.post_title_image_save_path),
        ),
    ]
